# from https://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
  - tools
  - platform-tools
    # The SDK version used to compile your project
  - android-25

# caching from https://stackoverflow.com/a/38772440
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - TRAVIS_SDK_PATH=/usr/local/android-sdk/licenses
  - secure: "Na7QEyUACs6m4mubocccHnGAyeAuEZHgnMB3OvB2Mur0kQQ68S7OUWWm16s4meEeVZnMBhUHb1tqamJDeKXTTKkPBVNA4UZhs/eFcftBBrQFAJA6HhKbdqwO+fEHJIaoa8Sa09z8QLmS9BhkB3a+/UvAkLeFsBPf5K3p6p1PKpSK7wNT6RoLN5kOWrlJoKYPexl1oXcu7zTz4/nSpr4M4WdTUoM1rM/4X1KDxeUQ0RDxwY4NP/6g+BVifXHOSKsQNpf0pkPzSIinuKr36n2BhjEQxuaHFTAamJArIcAhjt3xbY7OnCmOaaOe7UqaOPp2mR2HbcWov7GJqiyYuwWx+PCoQ1KhtPBgvFnpOlBmLhqlID+9c1gsQ8antoHApQmnhUKD2Osu+WAYk6P1mV27T6ysgpCGqHUNH20prsxovdnM6Zx2yTRwuD1UzUGl++B0i5LwCVuwqKqZHe0USH80ImPSxS2ztlaIxIEDHrYn5HoKv/vhr8mJtrfwtXXFp2OhEUfSWCF3IwRgJbnT4laoCDyBwKKXbiOc22cAOsMQ1yuLsGVD/4Yt/Gm5UcyOIM1JMCARQ7Q48gEcQR4u928S3g/1OdvfxTkVbFgqEhewNmYOkrF8QSCrMYVx//wJeZMgzBIOwl+dAOkojpaIDgFMLHn0pDF6fkUVIFeCqQtEiHw=" # TRANSIFEX_PASSWORD
  - secure: "cHs4XleLfH4MORfiqmbKx43+i/73V3rkiRtnt+aYNkZkDJCfkbAInKz4VQFPN0nTOkggEoWHHM7zxckI2RuITcdZEeHEgvWcrlkedKctXJM2i9IES5fpITLy0ZalXP0Hok9SAmE6tfRXEotkX5PUzIhCBM+NHCi3UIzeVF7b+ZYVd6vCZpTOwYA4gR2BBL8Z4gmp/cneCujas+xp4i0MbuIPIFfTnG1Bp3GYpBLOhCd+A2TS9DToSBxz1x9Ee+mdnfwgJwyGtRFffjU8Tk2h1ilVqzb7xi8u/N6ygzKBw2m1B+LVo7TDvb+MbsbGe0Wilm50yuGHTU+k6g5Ai9h/Y7EbdHNgB2ffoUswOMnnkuws/IBfdOLhGtt5YlaKvQ6eytnJ2nAkpmvmnoVFUTSD3Nzrrl93glunG4G9CycdT8g1LYhy2Pv3Oludkat5HDi/FL0FFjXFt+tND2GSyhYkip5y4utiuCR7jWlEBEfwxyYmpW/8qDxIqeISUkXkDSMrbvIrMpkQ2p9svCZkHrMbjS7Zio9a0iIGl5FxlyyYU1P7eQH9mxf2ZZupPDdgCbrNAurCZl2l7bGAK1ltc3QOXqCe9dDA8IqeZZ4APO0czdNfJpSrkcptnxPOOcNIa4iysVq6KR+vbP/qi8wwg3ZS0gZrLuM326RPVIYWd85ZLHs=" # GITHUB_TOKEN
  - secure: "QTNrLjaZmU4bZPlHZRXj0+YmNe1WBahjQBS8ApDJQWz/jpQeD7io4AijPs3Dfu5l01EMupBYwZ9GwX+3/kUFEtmW+Qrxc0xlh9MWTCdyYq+3fPT5sdt61EZwVBZsaItAZHKzdX0b9rquBTIK9oFBi9ReLlTxuFYVDCamhG3zoEq8yG/fv7TpUXdbTJIIigkvn6Vq2O6vOtAgBlaBvZX/ua/3d47C1n2IM6w2XsQRaFNTfs4/T5o6pU/0xTJrRhN1xI6otC2b1K75kR7UqSuuXAZw38ApSBFsladQHfi/XS9UnjRm6uAWIrIhKxFO2zF4hr3/9fLMT47VY4YVFieY1agLIwaldamQcyLWgCcnz7lH0yuaLvBOhkTW3nnXFbMugm4smE7YKMvUWpRiShDnAUr7Nigm1gDICSNMiwuSN/vxmYWk3J3vHWRp9OKQUHEasQrGXx9bIkAwJcHbkqh07UZPGIZL12EVFWXbUhe2kzeM/bgtx0bp2SHRaVUl0DHkt1zF0PYuHUAh8BPbAPvEK77Fuwd9M6lH40C6wdtdgUTtPS6gSk5FfoY3lmbJeDrJ+JGSUfvmfzZNfIo0o/J8mXcypC604bXVHZPo5Hk6577mEMdXfwH/ZW3rJ6aNuYqZdmFOIc7bPTERP2Xi+Drs9fiCk3yYg0FdtLx0mHagkio=" # keystore_password
  - secure: "UKX+DlBNu3uwPR9bjLC6bsqgwgjAkkeqE5jLxJtEpUZoBQDi8A1LL96IV1oAfOAyhhOjdAapUvcbtlOEaPZHUgNZzMbIwT4mrJ1pfEZh2DIKJpbnspSmMuD7/YC2QQ+DIn2ksL32/emFRvOKSha+8dsH7z8LJpVP18bgP0tDyhthNT0SJXO40m4QO+yUU7otVYvl7ywxgsUZFWPZhySIhaghD67qlsBREiQn8soHUlAFP0/tS+rzOX4JPyPZDk+B0A240VpCkMXpshSCgRp+eswpqp7uThbpjLe5LmReWpBIjn+6Xd2uhsGRQv6pfvA/b9FScvI+Rl3heX4wnM2R+LzWot1cpurGehvr7eVO4Cj+nsSRBdSEkx561ZfSnwGtFVpLUcMUrUKRqqrr2byPJK4oQuT0RrxK0WeJOYRRBhfN05luwFAsoDuXvMLRtLwItYkYab/K4Ewr8NnXdSacT/avBB2+61RS1yzipGm1KlO99ilk9/kSyiJaZGeE6O8ZVRxtjsCLw4Tq0vryrX8mS0hC+NLwQzuhfjiB3VDn6BYaI3aieyilxiQx4gjMCJ+u5gdmEcJPxqRLTIMZk8aYP7FP7ZmVSPmOouJaPcqY0eVucjm6hk7e9/vhwitzb0BQo8hD9ZUHndNvQBasZe20xHCy7CYEPZ5qgm3/YR9gL4A=" # keystore_alias_password
  - keystore_alias=key0

addons:
  apt:
    # see https://docs.travis-ci.com/user/installing-dependencies/
    update: true
    packages:
    - python3-pip

before_install:
# create signing key, see https://doubledot.dev/blog/2018-11-14-Continuous-Integration/
- openssl aes-256-cbc -K $encrypted_a03063b149e2_key -iv $encrypted_a03063b149e2_iv -in .travis/key.jks.enc -out .travis/key.jks -d

before_script:
# install sdkman from https://sdkman.io/
- curl -s "https://get.sdkman.io" | bash && source /home/travis/.sdkman/bin/sdkman-init.sh
# install gradle of a specific version, from https://gradle.org/install/#with-a-package-manager
- sdk install gradle 5.1.1
# install the licenses
# see https://developer.android.com/studio/intro/update#download-with-gradle
- mkdir -p "$TRAVIS_SDK_PATH"
- printf "d56f5187479451eabf01fb78af6dfcb131a6481e\n8933bad161af4178b1185d1a37fbf41ea5269c55\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > "$TRAVIS_SDK_PATH/android-sdk-license"

script:
# build and test
- ./scripts/generate-changelog.py
- gradle build check
- gradle assembleRelease
- ./scripts/runHTTPProxy.sh --compile
# use the build
- "find | grep '\\.apk'"
- .travis/release-apk
- .travis/debug-apk

before_deploy:
- mkdir apks
- cp `.travis/release-apk` apks/
- cp `.travis/debug-apk` apks/

deploy:
  # push the latest strings to translate
  - provider: script
    script: .travis/deploy_translation_sources
    skip_cleanup: true
    on:
      branch: master
  # push the release tag
  - provider: script
    script: .travis/create_release
    skip_cleanup: true
    on:
      branch: master
  # in the release tag, upload the apks
  - provider: releases
    api_key:
      secure: bvhMN07c2vgCBTH62fiF+XwK/4Vs0n6kIwP3Fv+emWgu7TUtEgn8Ypx2Bft3nKYZCZJa2/nM5BBqJ4OanSAzhiLT5u8PT6tbPAJRxe98mUYR090aUReHEUesWKuwFVvhpjp0G1obY7p2YrnxjugJrrr/rgr8Rps382h3kKws9cTyWg1vYlbvmzH2Ks//7lObU3UiGit61La4VYffkcYOEYCo4UQQsrCScnHokYmf9sorimNTSFBQvuaLZpJF91T++Xa2Bl5IsbGnE0gQ3bGEltmKKbukkvGCsmKjxNj3WMIoPfjZfF1D6P9koiWXGMncex4dsdAU3nGGfeyAJpNlQMsCHMEu+Phu7qZsaLJHeo1LIFrkRnkBegNxOWjP8VW9+cMvAwuCfwkJMqPJZRcBUy3RoBRgoXha1jaLTb4LMxLO+WSd4Qf1X5zw437XSiKHRnXc+8noKbvSknTsc4MygyO84chuvbX/i9qNpVGiWRXfnnMCZlGStvY0O8Aov+19wohM1crvaTaA1fZezJjjOCXE004tjjPMUw2plJccn7OVjb/K4F7WkZclbF+yJujOaeX3oYxpgZEsPb7dgyuIB7pGq40kJ8tJLbZaDaHteHvSYpfsFsrbK4B3fCHt3FOgjeA9oj+U9vwpF27GDgvs2XYPCM20W9UpZdFJljYokNw=
    file:
    - apks/*
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      repo: niccokunzmann/mundraub-android

